---
title: "02c_CLPN"
author: "Sglatt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!require("bootnet")) {install.packages("bootnet"); require("bootnet")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("glmnet")) {install.packages("glmnet"); require("glmnet")}
if (!require("igraph")) {install.packages("igraph"); require("igraph")}
if (!require("network")) {install.packages("network"); require("network")}
if (!require("networktools")) {install.packages("networktools"); require("networktools")}
if (!require("pcalg")) {install.packages("pcalg"); require("pcalg")}
if (!require("psychTools")) {install.packages("psychTools"); require("psychTools")}
if (!require("qgraph")) {install.packages("qgraph"); require("qgraph")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")}
```

# Cross lagged panel networks 
```{r Data}
RESST_3w <- readxl::read_xlsx("Raw_data/RESST_3_wave_data.xlsx") 

RESST_3w_all <- RESST_3w %>% filter(TP1_to_2 == 1) 

CLPN_all_resst <- RESST_3w_all %>% 
  dplyr::select(TP1_RESST_1,
         TP1_RESST_2,
         TP1_RESST_3,
         TP1_RESST_4,
         TP1_RESST_5,
         TP1_RESST_6,
         TP1_RESST_7,
         TP1_RESST_8,
         TP1_RESST_9,
         TP1_RESST_10,
         TP1_RESST_11,
         TP1_RESST_12,
         TP1_RESST_13,
         TP1_RESST_14,
         TP1_RESST_15,
         TP1_RESST_16,
         TP1_RESST_17,
         TP1_RESST_18,
         TP1_RESST_19,
         TP1_RESST_20,
         TP1_RESST_21, 
         TP2_RESST_1,
         TP2_RESST_2,
         TP2_RESST_3,
         TP2_RESST_4,
         TP2_RESST_5,
         TP2_RESST_6,
         TP2_RESST_7,
         TP2_RESST_8,
         TP2_RESST_9,
         TP2_RESST_10,
         TP2_RESST_11,
         TP2_RESST_12,
         TP2_RESST_13,
         TP2_RESST_14,
         TP2_RESST_15,
         TP2_RESST_16,
         TP2_RESST_17,
         TP2_RESST_18,
         TP2_RESST_19,
         TP2_RESST_20,
         TP2_RESST_21,
         )
```

```{r CLPN paths}

CLPN_all_resst_mat <- as.matrix(CLPN_all_resst) # DF to matrix

k <- 21
adjMat.all.fre <- matrix(0, k, k) # set up empty matrix of coefficients
rsquarelist <- rep(0, k)

for (i in 1:k){ 
  set.seed(100)
  lassoreg <- cv.glmnet(as.matrix(CLPN_all_resst_mat[,1:k]), CLPN_all_resst_mat[,(k+i)], 
                        family = "gaussian", alpha = 1, standardize = TRUE)
  lambda <- lassoreg$lambda.min 
  
  # rsquare[i] <- lassoreg$glmnet.fit$dev.ratio[which(lassoreg$lambda == lambda)]
  adjMat.all.fre[1:k,i] <- coef(lassoreg, s = lambda, exact = FALSE)[2:(k+1)]
} 

adjMat.all.fre2 <- adjMat.all.fre
#diag(adjMat.all.fre2) <- 0 
# set autoregressive paths to zero for visual ease
```

```{r CLPN Network viz}
nodenames <- c("R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9",
"R10", "R11", "R12", "R13", "R14", "R15", "R16", "R17", "R18",
"R19", "R20", "R21")
                   

groups_all <- list("self-worth"=c(1,2,3,4,5,6,7), 
                   "life worth"=c(8,9,10,11), 
                   "social worth" = c(12,13,14,15,16,17), 
                   "self-understanding"=c(18,19,20,21))

qgraph(adjMat.all.fre2, 
       legend = T,
       nodeNames = nodenames,
       #edge.labels = T, 
       palette = "colorblind", 
       layout = "spring", 
       posCol = "blue", 
       legend.cex = .35,
       vsize = 6
)
                   
qgraph(adjMat.all.fre2, 
       legend = T,
       nodeNames = nodenames,
       groups = groups_all,
       color=c("#99FFFF", "#CC99FF", "#FFCC99", "#FF99CC"), 
       #edge.labels = T, 
       palette = "colorblind", 
       layout = "spring", 
       posCol = "#00FF33", 
       legend.cex = .35, 
       vsize = 6 
)

# Figures
pdf("Output/CLPN_network.pdf", width = 10, height = 10)
qgraph(adjMat.all.fre2, 
       legend = T,
       nodeNames = nodenames,
       #edge.labels = T, 
       palette = "colorblind", 
       layout = "spring", 
       posCol = "blue", 
       legend.cex = .7,
       vsize = 7 
)
dev.off()

pdf("Output/CLPN_network_clusters.pdf", width = 10, height = 10)
qgraph(adjMat.all.fre2, 
       legend = T,
       nodeNames = nodenames,
       groups = groups_all,
       color=c("#99FFFF", "#CC99FF", "#FFCC99", "#FF99CC"),
       #edge.labels = T, 
       palette = "colorblind", 
       layout = "spring", 
       posCol = "#00FF33", 
       legend.cex = .7, 
       vsize = 6 
)
dev.off()
```

```{r CLPN bootnet function}
# Custom function for Bootnet for CLPN - I adapted from 2023 version

CLPN.mat.all.fre <- function(CLPN_all_resst_mat) {
  #create empty adjacency matrix
  adjMatCLPN.all.fre <- matrix(0,k,k)
  # run loop
  for (i in 1:k){

    lassoreg <- cv.glmnet(as.matrix(CLPN_all_resst_mat[,1:k]), CLPN_all_resst_mat[,(k+i)], 
                          family = "gaussian", alpha = 1, standardize = TRUE)
    lambda <- lassoreg$lambda.min 
    #  rsquare[i] <- lassoreg$glmnet.fit$dev.ratio[which(lassoreg$lambda == lambda)]
    adjMatCLPN.all.fre[1:k,i] <- coef(lassoreg, s = lambda, exact = FALSE)[2:(k+1)]
    #diag(adjMatCLPN.all.fre) <- 0
  }
  return(adjMatCLPN.all.fre)
}


network.all.fre <- estimateNetwork(CLPN_all_resst_mat, fun = CLPN.mat.all.fre, 
                           directed = T)

set.seed(123456)
boot1_all_frequency <- bootnet(network.all.fre, type = "nonparametric", nBoots = 500, directed = T,
                                statistics = c("edge","outExpectedInfluence", "inExpectedInfluence"),
                                ncores = 8)

set.seed(123456)
(boot2_all_frequency <- bootnet(network.all.fre,
                                type = "case",
                                nBoots = 500,
                                directed = T,
                                statistics = c("edge","outExpectedInfluence", "inExpectedInfluence")))

boot2_all_frequency$bootTable
corStability(boot2_all_frequency)

# Bootnet plots
plot(boot1_all_frequency, 
     labels = T, 
     legend = F,  
     order = "sample")

plot(boot1_all_frequency, "edge",
     plot = "difference",
     onlyNonZero = T, 
     order = "sample") 

plot(boot1_all_frequency, 
     "outExpectedInfluence", 
     plot = "difference",
     order = "sample")

plot(boot1_all_frequency, 
     "inExpectedInfluence", 
     plot = "difference",
     order = "sample")

plot(boot2_all_frequency,
     statistics = c("outExpectedInfluence", "inExpectedInfluence")) # Stability O and I inf

# Figures
pdf("Output/CLPN_network_edge_difference.pdf", width = 10, height = 10)
plot(boot1_all_frequency, "edge",
     plot = "difference",
     onlyNonZero = T, 
     order = "sample") 
dev.off()

pdf("OUtput/CLPN_network_boot_edges.pdf", width = 10, height = 10)
plot(boot1_all_frequency, 
     labels = T, 
     legend = F,  
     order = "sample")
dev.off()

pdf("Output/CLPN_in_out_centralities.pdf", width = 10, height = 10)
plot(boot2_all_frequency,
     statistics = c("outExpectedInfluence", "inExpectedInfluence")) 
dev.off()
```
 