---
title: "03_directed"
author: "Sglatt"
date: "`r Sys.Date()`"
output: github_document
keep_html: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
if (!require("bootnet")) {
  install.packages("bootnet")
  require("bootnet")
}
if (!require("dplyr")) {
  install.packages("dplyr")
  require("dplyr")
}
if (!require("ggplot2")) {
  install.packages("ggplot2")
  require("ggplot2")
}
if (!require("igraph")) {
  install.packages("igraph")
  require("igraph")
}
if (!require("mgm")) {
  install.packages("mgm")
  require("mgm")
}
if (!require("moments")) {
  install.packages("moments")
  require("moments")
}
if (!require("pcalg")) {
  install.packages("pcalg")
  require("pcalg")
}
if (!require("psych")) {
  install.packages("psych")
  require("psych")
}
if (!require("qgraph")) {
  install.packages("qgraph")
  require("qgraph")
}
if (!require("stats")) {
  install.packages("stats")
  require("stats")
}
if (!require("tidyverse")) {
  install.packages("tidyverse")
  require("tidyverse")
}

if (!require("BiocManager")) {
  install.packages("BiocManager")
  require("BiocManager")
}
BiocManager::install("graph")
BiocManager::install("RBGL")
```

# Folder for output  
```{r output}
if (!dir.exists("03_output")) {
  dir.create("03_output")
}
```

```{r Data and prep}
RESST_all <- read.csv("Created_data/RESST_merged_SG_2024-10-08.csv") # From "01a_data_processing"

RESST_all <- RESST_all %>%
  mutate(across(c(R1:R21), as.numeric))

FCI_items_1 <- RESST_all %>%
  dplyr::select(R1, R7, R8, R11, R13, R17, R20, R21)

FCI_items_2 <- RESST_all %>%
  dplyr::select(R1, R7, R8, R11, R13, R17, R20, R21, Q47, Q51)

abbrev_1 <- c("R1", "R7", "R8", "R11", "R13", "R17", "R20", "R21")

abbrev_2 <- c("R1", "R7", "R8", "R11", "R13", "R17", "R20", "R21", "SB2", "SB4")
```

# Recovery and suicide
```{r Base network 2}
fci_Network_eg <- estimateNetwork(FCI_items_2,
  labels = abbrev_2,
  default = "EBICglasso"
)

fci_Network_eg_w <- fci_Network_eg$graph
fci_Network_eg_w # weights matrix
mean(fci_Network_eg_w[lower.tri(fci_Network_eg_w)]) # density
smallworldIndex(qgraph(fci_Network_eg_w)) # small world index

p <- ncol(fci_Network_eg_w)
p
K <- solve(cov2cor(solve(diag(p) - fci_Network_eg_w)))
R2 <- 1 - 1 / diag(K)
R2

fci_graph_pred <- qgraph(fci_Network_eg_w,
  layout = "spring",
  theme = "colorblind",
  groups = NULL,
  vsize = 8,
  label.scale = TRUE,
  pie = R2,
  pieColor = rep("#377EB8", 1),
  label.prop = 0.8
)

# FCI L-val
averageLayout(fci_Network_eg, fci_graph_pred)
(L <- averageLayout(fci_Network_eg, fci_graph_pred))

pdf("03_output/FCI_2_base_net.pdf", width = 5, height = 5)
plot(fci_Network_eg,
  layout = "spring"
)
dev.off()

pdf("03_output/FCI_2_base_net_predict.pdf", width = 5, height = 5)
qgraph(fci_Network_eg_w,
  layout = "spring",
  theme = "colorblind",
  groups = NULL,
  vsize = 8,
  label.scale = TRUE,
  pie = R2,
  pieColor = rep("#377EB8", 1),
  label.prop = 0.8
)
dev.off()
```

```{r FCI 2}
set.seed(123456)
fci.output <- fci(
  suffStat = list(
    C = cov2cor(cov(FCI_items_2)),
    n = nrow(FCI_items_2)
  ),
  indepTest = gaussCItest,
  selectionBias = TRUE,
  labels = abbrev_2,
  alpha = 0.1,
  verbose = TRUE
)

# plot FCI graph
plot.fci.igraph <- function(fci) {
  require(igraph)
  amat <- fci@amat
  amat.dir <- amat
  amat.dir[amat.dir == 1 | amat.dir == 3] <- 0
  amat.dir[amat.dir == 2 & t(amat.dir) == 3] <- 1
  amat.dbl <- amat
  amat.dbl[amat.dbl == 2 | amat.dbl == 3] <- 0
  amat.tot <- amat.dir + amat.dbl
  amat.tot[amat.tot > 1] <- 1
  amat.col <- amat.tot
  amat.col[amat.col == 1 & t(amat.col) == 0] <- 3
  graph <- graph_from_adjacency_matrix(amat.tot, weighted = TRUE)
  graph.col <- graph_from_adjacency_matrix(amat.col, weighted = TRUE)
  E(graph)$color <- ifelse(E(graph.col)$weight == 3, "#99ff99", "white")
  l <- L
  plot(graph,
    edge.arrow.size = 0.5, vertex.size = 20, vertex.frame.color = "black",
    vertex.color = "white", vertex.label.color = "black",
    edge.curved = FALSE, rescale = TRUE, layout = l * 1.1
  )
}

plot.fci.igraph(fci.output)

pdf("03_output/FCI_2_causal.pdf", width = 5, height = 5)
plot.fci.igraph(fci.output)
dev.off()
```

# Plain recovery
```{r Base network 1}
fci_Network_eg <- estimateNetwork(FCI_items_1,
  labels = abbrev_1,
  default = "EBICglasso"
)

fci_Network_eg_w <- fci_Network_eg$graph
fci_Network_eg_w # weights matrix
mean(fci_Network_eg_w[lower.tri(fci_Network_eg_w)]) # density
smallworldIndex(qgraph(fci_Network_eg_w)) # small world index

p <- ncol(fci_Network_eg_w)
p
K <- solve(cov2cor(solve(diag(p) - fci_Network_eg_w)))
R2 <- 1 - 1 / diag(K)
R2

fci_graph_pred <- qgraph(fci_Network_eg_w,
  layout = "spring",
  theme = "colorblind",
  groups = NULL,
  vsize = 8,
  label.scale = TRUE,
  pie = R2,
  pieColor = rep("#377EB8", 1),
  label.prop = 0.8
)

# FCI L-val
averageLayout(fci_Network_eg, fci_graph_pred)
(L <- averageLayout(fci_Network_eg, fci_graph_pred))

pdf("03_output/FCI_1_base_net.pdf", width = 5, height = 5)
plot(fci_Network_eg,
  layout = "spring"
)
dev.off()

pdf("03_output/FCI_1_base_net_predict.pdf", width = 5, height = 5)
qgraph(fci_Network_eg_w,
  layout = "spring",
  theme = "colorblind",
  groups = NULL,
  vsize = 8,
  label.scale = TRUE,
  pie = R2,
  pieColor = rep("#377EB8", 1),
  label.prop = 0.8
)
dev.off()
```

```{r FCI 1}
set.seed(123456)
fci.output <- fci(
  suffStat = list(
    C = cov2cor(cov(FCI_items_1)),
    n = nrow(FCI_items_1)
  ),
  indepTest = gaussCItest,
  selectionBias = TRUE,
  labels = abbrev_1,
  alpha = 0.1,
  verbose = TRUE
)

plot.fci.igraph(fci.output)

pdf("03_output/FCI_1_causal.pdf", width = 5, height = 5)
plot.fci.igraph(fci.output)
dev.off()
```
